---
title: "Orthofinder - Brassicaceae"
author: "Miloš Duchoslav"
date: "2025-10"
output:
  github_document:
    toc: true
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# Setting NO evaluation of code chunks as default (needed for knitting of bash code without trying to run that)
knitr::opts_chunk$set(eval = FALSE)
```

# Introduction

This RMarkdown file (or its markdown version for GitHub) documents running of OrthoFinder tool to get orthology relationships between some Brassicaceae species.

This file includes:

1. BASH code that I ran at MetaCentrum (Czech national grid infrastructure) running PBS scheduling system for batch jobs.
2. R code that I ran locally.

### SW installation and versions

The SW installation instructions and versions of SW used is described in [0_Installation_of_SW.md](0_Installation_of_SW.md).


# Preparation of protein sequences

Here I describe the preparation of the data for the first run, then in the next section, I will add the data for the second run.

### Folders etc.
```{sh}
cd /storage/brno12-cerit/home/duchmil/Brassicaceae_orthology
mkdir brassicaceae_3
cd brassicaceae_3/
mkdir original_protein_fasta
mkdir renamed_protein_fasta_ncbi
mkdir renamed_protein_fasta_other
mkdir primary_transcripts
mkdir genomes_for_extracting_proteins
```

## Species with the downloadable primary transcripts
```{sh}
### Download of the protein sequences
cd /storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/original_protein_fasta

### Species with the downloadable primary transcripts

## A. thaliana
# downloading A. thaliana "representative gene model" from TAIR (Araport11)
wget 'https://www.arabidopsis.org/api/download-files/download?filePath=Proteins/Araport11_protein_lists/Araport11_pep_20250411_representative_gene_model.gz'
mv download\?filePath\=Proteins%2FAraport11_protein_lists%2FAraport11_pep_20250411_representative_gene_model.gz Araport11_pep_20250411_representative_gene_model.gz
gunzip Araport11_pep_20250411_representative_gene_model.gz
# # the file is encoded in UTF-8
# file -bi Araport11_pep_20250411_representative_gene_model
# # There are sometimes strange characters and the OrthoFinder has with it problem. Thus, I will convert it to us-ascii, with removal of invalid characters (option -c).
# iconv -c -f UTF-8 -t US-ASCII Araport11_pep_20220914_representative_gene_model -o Araport11_pep_20220914_representative_gene_model_cor.fasta
# renaming
cp Araport11_pep_20250411_representative_gene_model ../primary_transcripts/Arabidopsis_thaliana.fasta

## Rorippa islandica
# https://phytozome-next.jgi.doe.gov/info/Rislandica_v1_1
# This curl command from JGI Data Portal is probably only short-term working:
# curl --cookie jgi_session=/api/sessions/51ebfe2aa63f9400f9369bd81038003c --output R_islandica.zip -d "{\"ids\":{\"Phytozome-473\":[\"5f4058459a211ae42a1a2c03\",\"5f4058459a211ae42a1a2c01\"]}}" -H "Content-Type: application/json" # https://files.jgi.doe.gov/filedownload/
# unzip R_islandica.zip -d R_islandica
# gunzip R_islandica/Phytozome/PhytozomeV13/Rislandica/v1.1/annotation/*.gz

# copy from previous run
cp ../../brassicaceae_1/original_protein_fasta/R_islandica/Phytozome/PhytozomeV13/Rislandica/v1.1/annotation/Rislandica_473_v1.1.protein_primaryTranscriptOnly.fa .
cp Rislandica_473_v1.1.protein_primaryTranscriptOnly.fa ../primary_transcripts/Rorippa_islandica.fasta


## Cardamine amara
# Genome assembly and annotation from Marek Šlenker
# Hap2 should be better according to Violette
cp -v /auto/pruhonice1-ibot/nfs4/home/mslenker/Projects/ref/C_amara.C087_203/C087_203_hap2.longest_isoform.aa .
cp C087_203_hap2.longest_isoform.aa ../primary_transcripts/Cardamine_amara.fasta
```

## Species anotated at NCBI

List of all eukaryotic species annotated at NCBI can be found here:
<https://www.ncbi.nlm.nih.gov/refseq/annotation_euk/all/>

```{sh}
### Species anotated at NCBI
cd /storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/original_protein_fasta

# loop for downloading of protein fastas and GFFs
while IFS=$'\t' read -r species_long_name species accession
do
# download from NCBI API
curl -OJX GET "https://api.ncbi.nlm.nih.gov/datasets/v2alpha/genome/accession/"$accession"/download?include_annotation_type=PROT_FASTA,GENOME_GFF&filename="$accession".zip" -H "Accept: application/zip"
unzip $accession".zip" -d $accession
cp $accession"/ncbi_dataset/data/"$accession"/protein.faa" "../renamed_protein_fasta_ncbi/"$species".fasta"
cp $accession"/ncbi_dataset/data/"$accession"/genomic.gff" "../renamed_protein_fasta_ncbi/"$species".gff"
done < ../NCBI_annotated_genomes.txt # file with accession and species names to use


cd ../renamed_protein_fasta_ncbi/
# Rscript --verbose ../NCBI_longest_protein_executable.r B_oleracea.fasta B_oleracea.gff

# load R
module load r/4.1.3-gcc-10.2.1-6xt26dl

# loop for extracting the longest transcripts using my R script
species_names=$(cut -f 2 ../NCBI_annotated_genomes.txt)
echo $species_names
for species in $species_names
do
Rscript --verbose ../NCBI_longest_protein_executable.r $species".fasta" $species".gff"
done

# copy the files to the folder with all primary transcripts
cp longest_transcripts/*.fasta ../primary_transcripts/
```



## Species other than annotated by NCBI with available protein sequences 
```{sh}
### Species with available protein sequences other than annotated by NCBI
# Orthofinder script for extracting primary transcripts will be used for these.

cd /storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/original_protein_fasta/

## A. arenosa
# https://github.com/PaulGrini/Arabidopsis_assemblies/tree/main/01_arenosa_assembly
# Protein sequences previously extracted from genome sequence and annotation by AGAT
cp ~/arenosa_genome_grini/arenosa_grini_proteins.fasta .
# renaming
cp arenosa_grini_proteins.fasta ../renamed_protein_fasta_other/Arabidopsis_arenosa.fasta

## A. lyrata - Rawat annotation
# Rawat et al., “Improving the Annotation of Arabidopsis Lyrata Using RNA-Seq Data.”
# <https://doi.org/10.1371/journal.pone.0137391>
# Release date: 2015
# Protein sequences previously extracted from genome sequence and modified annotation by AGAT.
# Copied from local place: d:\!ecolgen\resources\translation of gff to proteins\output\LyV2_proteins_mod_parents.fasta
# Copy from previous run
cp ../../brassicaceae_1/original_protein_fasta/LyV2_proteins_mod_parents.fasta .
# renaming
cp LyV2_proteins_mod_parents.fasta ../renamed_protein_fasta_other/Arabidopsis_lyrata_Rawat.fasta

## C. hirsuta
# Gan et al. “The Cardamine Hirsuta Genome Offers Insight into the Evolution of Morphological Diversity.” Nature Plants 2, no. 11 (October 31, 2016): 1–7. https://doi.org/10.1038/nplants.2016.167.
# http://chi.mpipz.mpg.de/assembly.html
wget http://chi.mpipz.mpg.de/download/annotations/carhr38.aa.fa

# Adding gene ID to fasta headers (It is needed for Orthofinder script to get longest isoforms.)
# (awk by ChatGPT)
awk '/^>/ {print $0 " gene=" gensub(/^>([A-Za-z0-9]+)\.[0-9]+/, "\\1", "g"); next} {print}' carhr38.aa.fa | head -n 100
awk '/^>/ {print $0 " gene=" gensub(/^>([A-Za-z0-9]+)\.[0-9]+/, "\\1", "g"); next} {print}' carhr38.aa.fa > Cardamine_hirsuta_with_gene_IDs.fasta
cp Cardamine_hirsuta_with_gene_IDs.fasta ../renamed_protein_fasta_other/Cardamine_hirsuta.fasta
# wget http://chi.mpipz.mpg.de/download/annotations/carhr38.gff
# cp carhr38.gff ../renamed_protein_fasta_other/Cardamine_hirsuta.gff

## Cochlearia excelsa
# Bray, Sian M., Tuomas Hämälä, Min Zhou, Silvia Busoms, Sina Fischer, Stuart D. Desjardins, Terezie Mandáková, et al. “Kinetochore and Ionomic Adaptation to Whole-Genome Duplication in Cochlearia Shows Evolutionary Convergence in Three Autopolyploids.” Cell Reports 43, no. 8 (August 27, 2024). https://doi.org/10.1016/j.celrep.2024.114576.
# Data: https://doi.org/10.5061/dryad.ncjsxkt1s

# I was not able to download from Dryad using wget, I had to download the files using web browser.
# gunzip C_excelsa_V5_braker2_wRseq.aa.LTPG.fasta.gz
# Copy from previous run
cp ../../brassicaceae_1/original_protein_fasta/C_excelsa_V5_braker2_wRseq.aa.LTPG.fasta ../../brassicaceae_1/original_protein_fasta/C_excelsa_V5_braker2_wRseq.gff3 .
grep -c '>' C_excelsa_V5_braker2_wRseq.aa.LTPG.fasta # 54424

# It seems like there are only primary transcripts, I probably don't need to extract them.
grep -P -c "\tgene\t" C_excelsa_V5_braker2_wRseq.gff3 # 54424
grep -P -c "\tmRNA\t" C_excelsa_V5_braker2_wRseq.gff3 # 56280

# Adding gene ID to fasta headers (It is needed for Orthofinder script to get longest isoforms.)
# (awk by ChatGPT)
awk '/^>/ {print $0 " gene=" gensub(/^>([A-Za-z0-9]+)\.t[0-9]+/, "\\1", "g"); next} {print}' C_excelsa_V5_braker2_wRseq.aa.LTPG.fasta | head -n 100
awk '/^>/ {print $0 " gene=" gensub(/^>([A-Za-z0-9]+)\.t[0-9]+/, "\\1", "g"); next} {print}' C_excelsa_V5_braker2_wRseq.aa.LTPG.fasta > Cochlearia_excelsa_with_gene_IDs.fasta
cp Cochlearia_excelsa_with_gene_IDs.fasta ../renamed_protein_fasta_other/Cochlearia_excelsa.fasta



```

## Species without downloadable protein sequences

### Downloading genomes and annotations
```{sh}
### Species without downloadable protein sequences
cd /storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/genomes_for_extracting_proteins

## Arabis alpina
# Jiao et al. 2017 (https://doi.org/10.1101%2Fgr.213652.116)
# http://www.arabis-alpina.org/refseq.html, I used the version 5.1 of the genome (later than Jiao et al. 2017)
species=Arabis_alpina
mkdir $species
cd $species
wget http://www.arabis-alpina.org/data/ArabisAlpina/assemblies/V5.1/Arabis_alpina.MPIPZ.version_5.1.chr.all.fasta.gz
wget http://www.arabis-alpina.org/data/ArabisAlpina/assemblies/V5.1/A.alpina.modified.5.1.gff3.gz
# AGAT can read gzipped GFF, but not gzipped genome fasta
gunzip Arabis_alpina.MPIPZ.version_5.1.chr.all.fasta.gz
cd ..

# Download annotation of Conringia planisiliqua and Euclidium syriacum
# from supplementary files of Jiao et al. 2017 (https://doi.org/10.1101%2Fgr.213652.116)
wget https://genome.cshlp.org/content/suppl/2017/04/05/gr.213652.116.DC1/Supplemental_Data.zip
mv Supplemental_Data.zip Jiao_2017_Supplemental_Data.zip
unzip Jiao_2017_Supplemental_Data.zip
rm Arabis_alpina.MPIPZ.version_5.chr.all.liftOverV4.v3.gff3.gz

## Conringia planisiliqua
# Jiao et al. 2017 (https://doi.org/10.1101%2Fgr.213652.116)
# Genome annotation (GFF) is from supplementary data of Jiao et al. 2017.
accession=GCA_900108845.1
species=Conringia_planisiliqua
mkdir $species
cd $species
curl -OJX GET "https://api.ncbi.nlm.nih.gov/datasets/v2alpha/genome/accession/"$accession"/download?include_annotation_type=GENOME_FASTA&filename="$accession".zip" -H "Accept: application/zip"
unzip $accession".zip" -d $accession
cp $accession"/ncbi_dataset/data/"$accession"/"*".fna" ./$species"_genome.fasta"
# Geting annotation from downloaded supplements
mv ../$species*.gff.gz .
# Unzipping genome annotation
gunzip $species*.gff.gz
cd ..

## Euclidium syriacum
# Jiao et al. 2017 (https://doi.org/10.1101%2Fgr.213652.116)
# Genome annotation (GFF) is from supplementary data of Jiao et al. 2017.
accession=GCA_900116095.1
species=Euclidium_syriacum
mkdir $species
cd $species
curl -OJX GET "https://api.ncbi.nlm.nih.gov/datasets/v2alpha/genome/accession/"$accession"/download?include_annotation_type=GENOME_FASTA&filename="$accession".zip" -H "Accept: application/zip"
unzip $accession".zip" -d $accession
cp $accession"/ncbi_dataset/data/"$accession"/"*".fna" ./$species"_genome.fasta"
# Geting annotation from downloaded supplements
mv ../$species*.gff.gz .
# Unzipping genome annotation
gunzip $species*.gff.gz
cd ..


# There is a problem that the IDs (scaffold names) are different in annotation and in genome sequence.

# Changing scaffold names
sed -E 's/>([^ ]*)( [^ ]* [^ ]* genome assembly, contig: )(scaffold_[0-9]*)(.*)$/>\3\2\3\4/' Conringia_planisiliqua/Conringia_planisiliqua_genome.fasta > Conringia_planisiliqua/Conringia_planisiliqua_genome_seqnames_as_gff.fasta
sed -E 's/>([^ ]*)( [^ ]* [^ ]* genome assembly, contig: )(scaffold_[0-9]*)(.*)$/>\3\2\3\4/' Euclidium_syriacum/Euclidium_syriacum_genome.fasta > Euclidium_syriacum/Euclidium_syriacum_genome_seqnames_as_gff.fasta



```



### Extraction of protein sequences from genome and annotation (A. alpina, E. syriacum and C. planisiliqua) using AGAT

```{bash}
# interactive job
qsub -I -l select=1:ncpus=1:mem=8gb:scratch_local=10gb -l walltime=2:00:00

cd /storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/genomes_for_extracting_proteins


cd Arabis_alpina/

zgrep -P -c "\ttransposable_element_gene\t" A.alpina.modified.5.1.gff3.gz # 0
zgrep -P -c "\tgene\t" A.alpina.modified.5.1.gff3.gz # 34212

# run the AGAT container
singularity run /storage/brno12-cerit/home/duchmil/SW/agat/agat_1.4.0--pl5321hdfd78af_0.sif

## Protein sequences
# AGAT can read gzipped GFF, but not gzipped genome fasta
agat_sp_extract_sequences.pl -g A.alpina.modified.5.1.gff3.gz -f Arabis_alpina.MPIPZ.version_5.1.chr.all.fasta -p -o Arabis_alpina_proteins.fasta

exit

# counting the number of sequences
grep ">" Arabis_alpina_proteins.fasta -c
# 34212

# converting from folded fasta to unfolded fasta for better counting and checking for internal stop codons
awk '/^>/ { if(NR>1) print "";  printf("%s\n",$0); next; } { printf("%s",$0);}  END {printf("\n");}' < Arabis_alpina_proteins.fasta | grep \*[[:alpha:]] | wc -l
# There are 463 proteins with internal stop codons.

# checking for alternative transcripts
grep ".t2 " Arabis_alpina_proteins.fasta -c # 0
# It seems that there is always only one transcript per gene.

# copy protein sequences
# There are no alternative splicings so I can put it directly to primary_transcripts
cp Arabis_alpina_proteins.fasta ../../primary_transcripts/Arabis_alpina.fasta

cd ..


cd Conringia_planisiliqua

# The annotation contains also transposable_element_gene features with mRNA_TE_gene, exon and CDS subfeatures. 
# They have to be removed, otherwise the proteins encoded by these genes will be also extracted.
grep -P -c "\ttransposable_element_gene\t" Conringia_planisiliqua.MPIPZ_v1.annotation.TE.gff # 21515
grep -P -c "\tgene\t" Conringia_planisiliqua.MPIPZ_v1.annotation.TE.gff # 34766

# list of protein coding genes
grep -P "\tgene\t" Conringia_planisiliqua.MPIPZ_v1.annotation.TE.gff | cut -f 9 | sed "s/ID=//" | sed "s/;.*$//" | head
grep -P "\tgene\t" Conringia_planisiliqua.MPIPZ_v1.annotation.TE.gff | cut -f 9 | sed "s/ID=//" | sed "s/;.*$//" > Conringia_planisiliqua_protein_coding_genes.txt
wc -l Conringia_planisiliqua_protein_coding_genes.txt # 34766

# run the AGAT container
singularity run /storage/brno12-cerit/home/duchmil/SW/agat/agat_1.4.0--pl5321hdfd78af_0.sif

## filter to keep only protein coding genes and remove TEs
agat_sp_filter_feature_from_keep_list.pl --gff Conringia_planisiliqua.MPIPZ_v1.annotation.TE.gff --keep_list Conringia_planisiliqua_protein_coding_genes.txt -o Conringia_planisiliqua.MPIPZ_v1.annotation.without_TE.gff

# exit AGAT container
exit

grep -P -c "\ttransposable_element_gene\t" Conringia_planisiliqua.MPIPZ_v1.annotation.without_TE.gff # 0
grep -P -c "\tgene\t" Conringia_planisiliqua.MPIPZ_v1.annotation.without_TE.gff # 34766

# run the AGAT container
singularity run /storage/brno12-cerit/home/duchmil/SW/agat/agat_1.4.0--pl5321hdfd78af_0.sif

## Extract protein sequences
agat_sp_extract_sequences.pl -g Conringia_planisiliqua.MPIPZ_v1.annotation.without_TE.gff -f Conringia_planisiliqua_genome_seqnames_as_gff.fasta -p -o Conringia_planisiliqua_proteins.fasta

# exit AGAT container
exit

# counting the number of sequences
grep ">" Conringia_planisiliqua_proteins.fasta -c
# 34766

# converting from folded fasta to unfolded fasta for better counting and checking for internal stop codons
awk '/^>/ { if(NR>1) print "";  printf("%s\n",$0); next; } { printf("%s",$0);}  END {printf("\n");}' < Conringia_planisiliqua_proteins.fasta | grep \*[[:alpha:]] | wc -l
# There are 17 proteins with internal stop codons.

# checking for alternative transcripts
grep ".t2 " Conringia_planisiliqua_proteins.fasta -c # 0
# It seems that there is always only one transcript per gene.

# copy protein sequences
# There are no alterbative splicings so I can put it directly to primary_transcripts
cp Conringia_planisiliqua_proteins.fasta ../../primary_transcripts/Conringia_planisiliqua.fasta

cd ..


cd Euclidium_syriacum

# The annotation contains also transposable_element_gene features with mRNA_TE_gene, exon and CDS subfeatures. 
# They have to be removed, otherwise the proteins encoded by these genes will be also extracted.
grep -P -c "\ttransposable_element_gene\t" Euclidium_syriacum.MPIPZ_v1.annotation.TE.gff # 33000
grep -P -c "\tgene\t" Euclidium_syriacum.MPIPZ_v1.annotation.TE.gff # 33001

# list of protein coding genes
grep -P "\tgene\t" Euclidium_syriacum.MPIPZ_v1.annotation.TE.gff | cut -f 9 | sed "s/ID=//" | sed "s/;.*$//" | head
grep -P "\tgene\t" Euclidium_syriacum.MPIPZ_v1.annotation.TE.gff | cut -f 9 | sed "s/ID=//" | sed "s/;.*$//" > Euclidium_syriacum_protein_coding_genes.txt
wc -l Euclidium_syriacum_protein_coding_genes.txt # 33001

# run the AGAT container
singularity run /storage/brno12-cerit/home/duchmil/SW/agat/agat_1.4.0--pl5321hdfd78af_0.sif

## filter to keep only protein coding genes and remove TEs
agat_sp_filter_feature_from_keep_list.pl --gff Euclidium_syriacum.MPIPZ_v1.annotation.TE.gff --keep_list Euclidium_syriacum_protein_coding_genes.txt -o Euclidium_syriacum.MPIPZ_v1.annotation.without_TE.gff

## Extract protein sequences
agat_sp_extract_sequences.pl -g Euclidium_syriacum.MPIPZ_v1.annotation.without_TE.gff -f Euclidium_syriacum_genome_seqnames_as_gff.fasta -p -o Euclidium_syriacum_proteins.fasta

# exit AGAT container
exit

# counting the number of sequences
grep ">" Euclidium_syriacum_proteins.fasta -c
# 33001

# converting from folded fasta to unfolded fasta for better counting and checking for internal stop codons
awk '/^>/ { if(NR>1) print "";  printf("%s\n",$0); next; } { printf("%s",$0);}  END {printf("\n");}' < Euclidium_syriacum_proteins.fasta | grep \*[[:alpha:]] | wc -l
# There are 2 proteins with internal stop codons.

awk '/^>/ { if(NR>1) print "";  printf("%s\n",$0); next; } { printf("%s",$0);}  END {printf("\n");}' < Euclidium_syriacum_proteins.fasta | grep \*[[:alpha:]] -b1

# checking for alternative transcripts
grep ".t2 " Euclidium_syriacum_proteins.fasta -c # 0
# It seems that there is always only one transcript per gene.

# copy protein sequences
# There are no alterbative splicings so I can put it directly to primary_transcripts
cp Euclidium_syriacum_proteins.fasta ../../primary_transcripts/Euclidium_syriacum.fasta
```

## Protein sequences from newly assembled and annotated genomes
```{sh}
cd /storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/original_protein_fasta

## Cardamine glauca
# Genome assembly and annotation:
# Nezamivand-Chegini Mahnaz, Duchoslav Milos, ..., Kolar Filip 2025 (to be published)
cp -v /storage/brno12-cerit/home/duchmil/annotations/Cardamine_glauca_2025_06/annot_processing/Cardamine_glauca_CUNI_V1_annotation_v1.1_proteins.fasta .
cp -v Cardamine_glauca_CUNI_V1_annotation_v1.1_proteins.fasta ../renamed_protein_fasta_other/Cardamine_glauca.fasta

## Noccaea praecox
# Genome assembly and annotation:
# Nezamivand-Chegini Mahnaz, Duchoslav Milos, ..., Kolar Filip 2025 (to be published)
cp -v /storage/brno12-cerit/home/duchmil/annotations/Noccaea_praecox_2024_12/annot_processing/Noccaea_praecox_CUNI_V1_annotation_v1.1_proteins.fasta .
cp -v Noccaea_praecox_CUNI_V1_annotation_v1.1_proteins.fasta ../renamed_protein_fasta_other/Noccaea_praecox.fasta

## Aethionema saxatile
# Genome assembly and annotation:
# Nezamivand-Chegini Mahnaz, Duchoslav Milos, ..., Kolar Filip 2025 (to be published)
cp -v /storage/brno12-cerit/home/duchmil/annotations/Aethionema_saxatile_2025_06/annot_processing/Aethionema_saxatile_CUNI_V1_annotation_v1.0_proteins.fasta .
cp -v Aethionema_saxatile_CUNI_V1_annotation_v1.0_proteins.fasta ../renamed_protein_fasta_other/Aethionema_saxatile.fasta

## Erysimum linariifolium
# Genome assembly and annotation:
# Nezamivand-Chegini Mahnaz, Duchoslav Milos, ..., Kolar Filip 2025 (to be published)
cp -v /storage/brno12-cerit/home/duchmil/annotations/Erysimum_linariifolium_2025_09/annot_processing/Erysimum_linariifolium_CUNI_V1_annotation_v1.0_proteins.fasta .
cp -v Erysimum_linariifolium_CUNI_V1_annotation_v1.0_proteins.fasta ../renamed_protein_fasta_other/Erysimum_linariifolium.fasta

## Odontarrhena muralis
# Genome assembly and annotation:
# Nezamivand-Chegini Mahnaz, Duchoslav Milos, ..., Kolar Filip 2025 (to be published)
cp -v /storage/brno12-cerit/home/duchmil/annotations/Odontarrhena_muralis_2025_10/annot_processing/Odontarrhena_muralis_CUNI_V1_annotation_v1.0_proteins.fasta .
cp -v Odontarrhena_muralis_CUNI_V1_annotation_v1.0_proteins.fasta ../renamed_protein_fasta_other/Odontarrhena_muralis.fasta

## Alyssum gmelinii
# Genome assembly and annotation:
# Nezamivand-Chegini Mahnaz, Duchoslav Milos, ..., Kolar Filip 2025 (unpublished)
cp -v /storage/brno12-cerit/home/duchmil/annotations/Alyssum_gmelinii_2025_10_V3/annot_processing/Alyssum_gmelinii_CUNI_V3_annotation_v3.0_proteins.fasta .
cp -v Alyssum_gmelinii_CUNI_V3_annotation_v3.0_proteins.fasta ../renamed_protein_fasta_other/Alyssum_gmelinii.fasta



```


## Extraction of primary transcripts using Orthofinder script
```{bash}
### Extraction of primary transcripts using Orthofinder script

# loading Python and the modules needed
# module load python
module add python36-modules-gcc

# test that Orthofinder is running
/storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/OrthoFinder_source/orthofinder.py -h

## taking only the longest transcript using Orthofinder script
cd /storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/renamed_protein_fasta_other/
for f in *.fasta ; do python /storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/OrthoFinder_source/tools/primary_transcript.py $f ; done
# Note: This does not work properly for NCBI data.

# This did not remove any transcripts from Cochlearia_excelsa, however, there were probably already only primary transcripts (see before).


# Copying files
cp -v primary_transcripts/*.fasta ../primary_transcripts/
```

### Removing Rorippa
```{sh}
cd /storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/primary_transcripts/
rm -v Rorippa_islandica.fasta
```

## Cleaning fasta files

A. thaliana fasta file contains non-ASCII character which is needed to be removed.
```{sh}
cd /storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/primary_transcripts

# Show the problematic character
grep --color='auto' -P -n "[^\x00-\x7F]" *
grep --color='auto' -P -n "[^\x00-\x7F]" * | iconv -f utf-8 -t ascii//TRANSLIT

iconv -f utf-8 -t ascii//TRANSLIT Arabidopsis_thaliana.fasta -o Arabidopsis_thaliana_clean.fasta

diff Arabidopsis_thaliana.fasta Arabidopsis_thaliana_clean.fasta

mv Arabidopsis_thaliana_clean.fasta Arabidopsis_thaliana.fasta

```




# Orthofinder run

## Brassicaceae_3 run

22 species, 23 input files (two different annotations for Arabidopsis_lyrata)  
Input fasta files:

Aethionema_saxatile.fasta  
Alyssum_gmelinii.fasta  
Arabidopsis_arenosa.fasta  
Arabidopsis_lyrata_NCBI.fasta  
Arabidopsis_lyrata_Rawat.fasta  
Arabidopsis_thaliana.fasta  
Arabis_alpina.fasta  
Brassica_napus.fasta  
Brassica_oleracea.fasta  
Brassica_rapa.fasta  
Camelina_sativa.fasta  
Capsella_rubella.fasta  
Cardamine_amara.fasta  
Cardamine_glauca.fasta  
Cardamine_hirsuta.fasta  
Cochlearia_excelsa.fasta  
Conringia_planisiliqua.fasta  
Erysimum_linariifolium.fasta  
Euclidium_syriacum.fasta  
Eutrema_salsugineum.fasta  
Noccaea_praecox.fasta  
Odontarrhena_muralis.fasta  
Raphanus_sativus.fasta  


```{bash}
### Metacentrum script

#PBS -N orthofinder_brassicaceae
#PBS -l select=1:ncpus=8:mem=32gb:scratch_local=200gb
#PBS -l walltime=23:50:00 
#PBS -m ae

# define a DATADIR variable: directory where the input files are taken from and where output will be copied to
DATADIR=/storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3

# append a line to a file "jobs_info.txt" containing the ID of the job, the hostname of node it is run on and the path to a scratch directory
# this information helps to find a scratch directory in case the job fails and you need to remove the scratch directory manually 
echo "$PBS_JOBID is running on node `hostname -f` in a scratch directory $SCRATCHDIR" >> $DATADIR/jobs_info.txt

# loading Python and the modules needed
module add python36-modules-gcc

# test if scratch directory is set
# if scratch directory is not set, issue error message and exit
test -n "$SCRATCHDIR" || { echo >&2 "Variable SCRATCHDIR is not set!"; exit 1; }

# copy Orthofinder
cp -r /storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/OrthoFinder_source $SCRATCHDIR || { echo >&2 "Error while copying Orthofinder file(s)!"; exit 2; }

# copy input files to scratch directory
# if the copy operation fails, issue error message and exit
cp -r $DATADIR/primary_transcripts $SCRATCHDIR || { echo >&2 "Error while copying input file(s)!"; exit 2; }

# move into scratch directory
cd $SCRATCHDIR 

# running OrthoFinder
$SCRATCHDIR/OrthoFinder_source/orthofinder.py -y -t 8 -f $SCRATCHDIR/primary_transcripts/ -o orthofinder_results -n brassicaceae_3

# move the output to user's DATADIR or exit in case of failure
cp -r orthofinder_results $DATADIR/ || { echo >&2 "Result file(s) copying failed (with a code $?) !!"; exit 4; }

# clean the SCRATCH directory
clean_scratch

# Resources used: 5 h 43 min, 53% CPU, 16 GB memory.
```







