---
title: "Phylogenomic tree"
author: "Miloš Duchoslav"
date: "2026-10"
output:
  github_document:
    toc: true
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# Setting NO evaluation of code chunks as default (needed for knitting of bash code without trying to run that)
knitr::opts_chunk$set(eval = FALSE)
```

# Introduction

This RMarkdown file (or its markdown version for GitHub) documents calculation of phylogenomic tree of the species included in OrthoFinder, using the OrthoFinder orthogroups.

This file includes BASH code that I ran at MetaCentrum (Czech national grid infrastructure) running PBS scheduling system for batch jobs. The code was partly written by AI.

## Strategy

There are just 3 single copy orthogroups, which is a little data to calculate reliable tree. The reasons are probably polyploids like *Brassica napus* and *Camelina sativa* (see [Comparative_Genomics_Statistics_heatmaps](figs_and_stats/Comparative_Genomics_Statistics_heatmaps.pdf)). To get good data, I will use orthogroups with all species present and allow there several paralogs. This will be mostly very similar paralogs obtained recently by whole genome duplication or tandem duplication. I will randomly select one paralog per species that will be retained for the calculation of the tree.

## SW installation and versions

The SW installation instructions and versions of SW used is described in [Installation_of_SW.md](Installation_of_SW.md).


# Data preparation

## Script to get distribution of number of orthogroups with different numbers of genes

Just for orthogroups with all species present.

```{sh}
cd /storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/
mkdir phylo_tree
cd /storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/phylo_tree
mkdir input_orthogroups

GENECOUNT="../orthofinder_results/Results_brassicaceae_3/Orthogroups/Orthogroups.GeneCount.tsv"

awk '
BEGIN { FS="\t" }

NR > 1 {
    all_present = 1

    for (i = 2; i <= NF - 1; i++) {
        if ($i == 0) {
            all_present = 0
            break
        }
    }

    if (all_present)
        print $NF
}
' ${GENECOUNT} |
sort -n |
uniq -c
```


```
      3 23
     49 24
    311 25
   1392 26
   1327 27
    887 28
    594 29
    633 30
    820 31
    855 32
    654 33
    414 34
    304 35
    288 36
    298 37
    220 38
    153 39
    124 40
     98 41
     76 42
     74 43
     68 44
     63 45
     73 46
     75 47
     62 48
     71 49
    105 50
    ... (not full result)
```


```{sh}
GENECOUNT="../orthofinder_results/Results_brassicaceae_3/Orthogroups/Orthogroups.GeneCount.tsv"
MAX_GENES=30

OUT_PREFIX="input_orthogroups/complete_orthogroups_max${MAX_GENES}"

echo "Input file: ${GENECOUNT}"
echo "Maximum number of genes per orthogroup: ${MAX_GENES}"
echo

# Overwrite existing output files
> "${OUT_PREFIX}.tsv"
> "${OUT_PREFIX}.ids.txt"

awk -v maxgenes="$MAX_GENES" \
    -v outfile="${OUT_PREFIX}.tsv" \
    -v idfile="${OUT_PREFIX}.ids.txt" '
BEGIN {
    FS = OFS = "\t"
}

NR == 1 {
    # OrthoFinder GeneCount table:
    # column 1 = Orthogroup
    # columns 2...(NF-1) = species
    # last column = Total

    nspecies = NF - 2

    print "Number of species detected:", nspecies > "/dev/stderr"

    print $0 >> outfile
    next
}

{
    all_present = 1

    # Check whether every species has at least one gene
    for (i = 2; i <= NF - 1; i++) {
        if ($i == 0) {
            all_present = 0
            break
        }
    }

    total_genes = $NF

    if (all_present) {
        complete++

        if (total_genes <= maxgenes) {
            retained++
            print $0 >> outfile
            print $1 >> idfile
        }
    }
}

END {
    print ""
    print "Summary:"
    print "Complete orthogroups (all species present):", complete
    print "Complete orthogroups with <=", maxgenes, "genes:", retained
}
' "$GENECOUNT"

echo
echo "Output files:"
echo "  ${OUT_PREFIX}.tsv"
echo "  ${OUT_PREFIX}.ids.txt"

```

```
Number of species detected:     23

Summary:
Complete orthogroups (all species present):     11890
Complete orthogroups with <=    30      genes:  5196

Output files:
  input_orthogroups/complete_orthogroups_max30.tsv
  input_orthogroups/complete_orthogroups_max30.ids.txt
```

## Add species names to protein names in fasta files before alignment

Just for orthogroups that will be used for alignment.
```{sh}
cd /storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/phylo_tree


############################
# User-defined variables
############################

# OrthoFinder table with genes separated by species
ORTHOGROUPS_TSV="../orthofinder_results/Results_brassicaceae_3/Orthogroups/Orthogroups.tsv"

# Original OrthoFinder orthogroup FASTA files
INPUT_DIR="../orthofinder_results/Results_brassicaceae_3/Orthogroup_Sequences"

# Selected orthogroups
ORTHOGROUP_LIST="input_orthogroups/complete_orthogroups_max30.ids.txt"

# Output directory for renamed FASTA files
OUTPUT_DIR="input_orthogroups/renamed_fastas"

mkdir -p "$OUTPUT_DIR"

echo "Starting FASTA header renaming"
echo "Orthogroups table:  $ORTHOGROUPS_TSV"
echo "Orthogroup list:    $ORTHOGROUP_LIST"
echo "Input directory:    $INPUT_DIR"
echo "Output directory:   $OUTPUT_DIR"
echo

############################
# Rename FASTA headers
############################

awk \
    -v input_dir="$INPUT_DIR" \
    -v output_dir="$OUTPUT_DIR" '
    
BEGIN {
    FS = OFS = "\t"
}

################################
# First input: selected OG IDs
################################

ARGIND == 1 {

    # Remove possible Windows carriage return
    gsub(/\r/, "")

    if ($1 != "")
        selected[$1] = 1

    next
}

################################
# Second input: Orthogroups.tsv
################################

ARGIND == 2 && FNR == 1 {

    # Store species names from header
    for (i = 2; i <= NF; i++) {

        species[i] = $i

        # Remove Windows carriage returns
        gsub(/\r/, "", species[i])

        # Replace spaces with underscores
        gsub(/ /, "_", species[i])
    }

    next
}

ARGIND == 2 {

    og = $1

    # Ignore orthogroups that were not selected
    if (!(og in selected))
        next

    print "Processing: " og > "/dev/stderr"

    ################################
    # Build map only for this OG
    ################################

    delete gene_species

    for (i = 2; i <= NF; i++) {

        field = $i

        # Remove Windows carriage returns
        gsub(/\r/, "", field)

        if (field == "")
            continue

        # Multiple genes in one species are comma-separated
        n = split(field, genes, ", ")

        for (j = 1; j <= n; j++) {

            gene = genes[j]
            gsub(/\r/, "", gene)

            gene_species[gene] = species[i]
        }
    }

    ################################
    # Rename corresponding FASTA
    ################################

    infile  = input_dir "/" og ".fa"
    outfile = output_dir "/" og ".fa"

    # Make sure an existing output is overwritten
    printf "" > outfile
    close(outfile)

    found_fasta = 0

    while ((getline line < infile) > 0) {

        found_fasta = 1

        if (line ~ /^>/) {

            header = substr(line, 2)
            gsub(/\r/, "", header)

            # Original gene ID = first whitespace-delimited field
            split(header, x, /[[:space:]]+/)
            gene = x[1]

            if (gene in gene_species) {
                print ">" gene_species[gene] "|" gene >> outfile
            }
            else {
                print ">" gene >> outfile
                print "WARNING: Species not found for gene " gene \
                    " in " og > "/dev/stderr"
            }
        }
        else {
            gsub(/\r/, "", line)
            print line >> outfile
        }
    }

    close(infile)
    close(outfile)

    if (!found_fasta)
        print "WARNING: FASTA file not found or empty: " infile \
            > "/dev/stderr"

    processed[og] = 1
}

END {

    n_selected = 0
    n_processed = 0

    for (og in selected) {
        n_selected++

        if (og in processed)
            n_processed++
        else
            print "WARNING: Selected orthogroup not found in Orthogroups.tsv: " og \
                > "/dev/stderr"
    }

    print ""
    print "Summary:"
    print "Selected orthogroups:", n_selected
    print "Processed orthogroups:", n_processed
}

' "$ORTHOGROUP_LIST" "$ORTHOGROUPS_TSV"

echo
echo "Finished."
echo "Renamed FASTA files:"
echo "  $OUTPUT_DIR"
```

## Select random sequence for each species in each orthogroup

In this step I will get single-copy orthologues. Foer each species, if there are several paralogs, one will be selected randomly. This shouldn't be making much bias, because I selected orthogroups with only few paralogs (at least one sequence for each of 23 species and maximally 30 sequences). Most of the paralogs are probably duplications within species or copies from different ancestors in allopolyploids like *Brassica napus*.

```{sh}
cd /storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/phylo_tree


############################
# User-defined variables
############################

# Directory with renamed FASTA files
INPUT_DIR="input_orthogroups/renamed_fastas"

# Directory for FASTA files with one random sequence per species
OUTPUT_DIR="input_orthogroups/random_single_copy_fastas"

# Random seed for reproducibility
SEED=12345

############################
# Setup
############################

mkdir -p "$OUTPUT_DIR"

echo "Starting random sequence selection"
echo "Input directory:  $INPUT_DIR"
echo "Output directory: $OUTPUT_DIR"
echo "Random seed:      $SEED"
echo

############################
# Process FASTA files
############################

for infile in "$INPUT_DIR"/*.fa; do

    filename=$(basename "$infile")
    outfile="${OUTPUT_DIR}/${filename}"

    echo "Processing: $filename"

    awk -v seed="$SEED" '

    BEGIN {
        srand(seed)
        record = ""
    }

    function store_record(    sp) {

        if (header == "")
            return

        # Species name is the part before "|"
        split(header, x, "|")
        sp = x[1]

        count[sp]++

        headers[sp, count[sp]] = header
        seqs[sp, count[sp]] = sequence
    }

    /^>/ {

        # Store previous sequence
        store_record()

        header = substr($0, 2)
        sequence = ""

        next
    }

    {
        sequence = sequence $0
    }

    END {

        # Store final sequence
        store_record()

        # Select one random sequence per species
        for (sp in count) {

            chosen = int(rand() * count[sp]) + 1

            print ">" headers[sp, chosen]
            print seqs[sp, chosen]
        }
    }

    ' "$infile" > "$outfile"

done

echo
echo "Finished random sequence selection."
echo "Output directory:"
echo "  $OUTPUT_DIR"
```

### Checking results

```{sh}
ls $INPUT_DIR | wc -l
ls $OUTPUT_DIR | wc -l

grep '>' $INPUT_DIR/OG0018051.fa | sort
echo ""
grep '>' $OUTPUT_DIR/OG0018051.fa | sort

grep '>' $INPUT_DIR/OG0009637.fa | sort
echo ""
grep '>' $OUTPUT_DIR/OG0009637.fa | sort

```


# MAFFT alignment of orthogroups

```{sh}
### Metacentrum script

#!/bin/bash
#PBS -N mafft_orthogroups
#PBS -l select=1:ncpus=16:mem=2gb:scratch_local=10gb
#PBS -l walltime=1:00:00
#PBS -m ae

set -euo pipefail

############################
# User-defined variables
############################

# Directory with OrthoFinder orthogroup FASTA files
INPUT_DIR="/storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/phylo_tree/input_orthogroups/random_single_copy_fastas"

# File containing selected orthogroup IDs, one per line
ORTHOGROUP_LIST="/storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/phylo_tree/input_orthogroups/complete_orthogroups_max30.ids.txt"

# Directory for MAFFT alignments
OUTPUT_DIR="/storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/phylo_tree/mafft_alignments"

# Number of parallel MAFFT jobs
NCPU=16

############################
# Environment
############################

module load mafft

mkdir -p "$OUTPUT_DIR"

cd "$OUTPUT_DIR"

echo "Starting MAFFT alignments"
echo "Input directory:    $INPUT_DIR"
echo "Orthogroup list:    $ORTHOGROUP_LIST"
echo "Output directory:   $OUTPUT_DIR"
echo "Parallel jobs:      $NCPU"
echo "Start time:         $(date "+%Y-%m-%d %H:%M:%S")"
echo "MAFFT version:"
mafft --version 2>&1
echo

############################
# Alignment function
############################

align_one() {

    og="$1"

    # Remove possible Windows carriage returns
    og="${og//$'\r'/}"

    # Skip empty lines
    [[ -z "$og" ]] && return

    infile="${INPUT_DIR}/${og}.fa"
    outfile="${OUTPUT_DIR}/${og}.aln.fa"

    # Check whether the input file exists
    if [[ ! -f "$infile" ]]; then
        echo "WARNING: Input file not found: $infile" >&2
        return
    fi

    # Skip already completed alignments
    if [[ -s "$outfile" ]]; then
        echo "Skipping existing alignment: $og"
        return
    fi

    echo "Aligning: $og"

    mafft \
        --auto \
        --thread 1 \
        "$infile" \
        > "$outfile"
}

export -f align_one
export INPUT_DIR
export OUTPUT_DIR

############################
# Run selected orthogroups
############################

grep -v '^[[:space:]]*$' "$ORTHOGROUP_LIST" |
    xargs -n 1 -P "$NCPU" bash -c 'align_one "$1"' _

############################
# Summary
############################

N_SELECTED=$(grep -cv '^[[:space:]]*$' "$ORTHOGROUP_LIST")

N_OUTPUT=$(find "$OUTPUT_DIR" \
    -maxdepth 1 \
    -type f \
    -name "*.aln.fa" \
    -size +0c |
    wc -l)

echo
echo "MAFFT alignment finished"
echo "Selected orthogroups: $N_SELECTED"
echo "Completed alignments: $N_OUTPUT"
echo "End time:             $(date "+%Y-%m-%d %H:%M:%S")"

# clean the SCRATCH directory
clean_scratch

# Resources:
# With 32 CPUs: Just 4 min, 0,87 GB memory, 76 % CPU
# With 16 CPUs: Just 6,5 min, 0,67 GB memory, 83 % CPU
```

```{sh}
cd /storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/metacentrum_scripts
qsub mafft_orthogroups.bash
```

# Trimming alignments using TrimAl

Trim parts of alignments with low informative value.

It takes just few minutes with 1 CPU, so it is not really needed to submit it as a job. The best would be ineractive job.

```{sh}

############################
# User-defined variables
############################

# Directory with MAFFT alignments
INPUT_DIR="/storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/phylo_tree/mafft_alignments"

# Directory for trimmed alignments
OUTPUT_DIR="/storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/phylo_tree/trimmed_alignments"

# Number of parallel trimAl jobs
NCPU=1

############################
# Environment
############################

module load trimal

mkdir -p "$OUTPUT_DIR"

cd "$OUTPUT_DIR"

echo "Starting trimAl trimming"
echo "Input directory:    $INPUT_DIR"
echo "Output directory:   $OUTPUT_DIR"
echo "Parallel jobs:      $NCPU"
echo "Start time:         $(date "+%Y-%m-%d %H:%M:%S")"
echo

############################
# Trimming function
############################

trim_one() {

    infile="$1"

    filename=$(basename "$infile")
    og="${filename%.aln.fa}"

    outfile="${OUTPUT_DIR}/${og}.trim.fa"

    # Skip already completed trimming
    if [[ -s "$outfile" ]]; then
        echo "Skipping existing alignment: $og"
        return
    fi

    echo "Trimming: $og"

    trimal \
        -in "$infile" \
        -out "$outfile" \
        -automated1
}

export -f trim_one
export OUTPUT_DIR

############################
# Run alignments in parallel
############################

find "$INPUT_DIR" \
    -maxdepth 1 \
    -type f \
    -name "*.aln.fa" \
    -print0 |
    xargs -0 -n 1 -P "$NCPU" bash -c 'trim_one "$1"' _

############################
# Summary
############################

N_INPUT=$(find "$INPUT_DIR" \
    -maxdepth 1 \
    -type f \
    -name "*.aln.fa" |
    wc -l)

N_OUTPUT=$(find "$OUTPUT_DIR" \
    -maxdepth 1 \
    -type f \
    -name "*.trim.fa" \
    -size +0c |
    wc -l)

echo
echo "trimAl trimming finished"
echo "Input alignments:   $N_INPUT"
echo "Trimmed alignments: $N_OUTPUT"
echo "End time:           $(date "+%Y-%m-%d %H:%M:%S")"

# clean_scratch
```

# Modify sequence names

Leave just species in sequence names, otherwise it will not be well concatenated by IQ-TREE.
 
```{sh}
cd /storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/phylo_tree/trimmed_alignments

mkdir -p ../trimmed_alignments_2

for f in *.trim.fa; do
    sed -E 's/^>([^|]+)\|.*/>\1/' "$f" > "../trimmed_alignments_2/${f%.trim.fa}.species.trim.fa"
done

```
 



# IQ-TREE calculation of tree for concatenated fasta

## Testing script

```{sh}
### Metacentrum script

#!/bin/bash
#PBS -N iqtree_species_tree_test_2
#PBS -l select=1:ncpus=32:mem=48gb:scratch_local=100gb
#PBS -l walltime=2:00:00
#PBS -m ae

set -euo pipefail

############################
# User-defined variables
############################

# Directory with trimmed locus alignments
ALIGN_DIR="/storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/phylo_tree/trimmed_alignments_2_test"

# Output directory
OUTPUT_DIR="/storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/phylo_tree/iqtree_species_tree_test_2"

# Output prefix
PREFIX="brassicaceae_species_tree"

# Number of CPUs
NCPU=32

############################
# Environment
############################

# append a line to a file "jobs_info.txt" containing the ID of the job, the hostname of node it is run on and the path to a scratch directory
# this information helps to find a scratch directory in case the job fails and you need to remove the scratch directory manually 
echo "$PBS_JOBID is running on node `hostname -f` in a scratch directory $SCRATCHDIR" | ts '[%Y-%m-%d %H:%M:%S]' >> $PBS_O_WORKDIR/jobs_info.txt

# test if scratch directory is set
# if scratch directory is not set, issue error message and exit
test -n "$SCRATCHDIR" || { echo >&2 "Variable SCRATCHDIR is not set!"; exit 1; }

# move into scratch directory
cd $SCRATCHDIR

# copy input data
mkdir iqtree_input
cp ${ALIGN_DIR}/* iqtree_input

# dir for output
mkdir iqtree_output

# load SW
module load iqtree

echo "Starting IQ-TREE species tree inference"
echo "Alignment directory: $ALIGN_DIR"
echo "Output directory:    $OUTPUT_DIR"
echo "CPUs:                $NCPU"
echo "Start time:          $(date "+%Y-%m-%d %H:%M:%S")"
echo
echo "IQ-TREE version:"
iqtree3-mpi --version 2>&1
echo

############################
# Run IQ-TREE
############################

iqtree3-mpi \
    -p "${SCRATCHDIR}/iqtree_input" \
    --seqtype AA \
    -m MFP+MERGE \
    -rcluster 10 \
    -B 1000 \
    -alrt 1000 \
    -T "$NCPU" \
    --prefix "${SCRATCHDIR}/iqtree_output/${PREFIX}"


# copy output data
mkdir -p "$OUTPUT_DIR"
cp -R ${SCRATCHDIR}/iqtree_output/* $OUTPUT_DIR


############################
# Summary
############################

echo
echo "IQ-TREE analysis finished"
echo "End time: $(date "+%Y-%m-%d %H:%M:%S")"
echo
echo "Main output tree:"
echo "  ${OUTPUT_DIR}/${PREFIX}.treefile"

clean_scratch

# Resources:
# For 8 orthogroups
# With 32 CPUs: 15 min, 0,27 GB memory, 14 % CPU
```

```{sh}
cd /storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/metacentrum_scripts
qsub iqtree_species_tree_test_2.bash
```

## Running IQ-TREE on complete data

```{sh}
### Metacentrum script

#!/bin/bash
#PBS -N iqtree_species_tree
#PBS -l select=1:ncpus=32:mem=128gb:scratch_local=100gb
#PBS -l walltime=168:00:00
#PBS -m ae

set -euo pipefail

############################
# User-defined variables
############################

# Directory with trimmed locus alignments
ALIGN_DIR="/storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/phylo_tree/trimmed_alignments_2"

# Output directory
OUTPUT_DIR="/storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/phylo_tree/iqtree_species_tree"

# Output prefix
PREFIX="brassicaceae_species_tree"

# Number of CPUs
NCPU=32

############################
# Environment
############################

# append a line to a file "jobs_info.txt" containing the ID of the job, the hostname of node it is run on and the path to a scratch directory
# this information helps to find a scratch directory in case the job fails and you need to remove the scratch directory manually 
echo "$PBS_JOBID is running on node `hostname -f` in a scratch directory $SCRATCHDIR" | ts '[%Y-%m-%d %H:%M:%S]' >> $PBS_O_WORKDIR/jobs_info.txt

# test if scratch directory is set
# if scratch directory is not set, issue error message and exit
test -n "$SCRATCHDIR" || { echo >&2 "Variable SCRATCHDIR is not set!"; exit 1; }

# move into scratch directory
cd $SCRATCHDIR

echo "Start copying input data." | ts '[%Y-%m-%d %H:%M:%S]'

# copy input data
mkdir iqtree_input
cp ${ALIGN_DIR}/* iqtree_input

echo "Input data copying done." | ts '[%Y-%m-%d %H:%M:%S]'

# dir for output
mkdir iqtree_output

# load SW
module load iqtree

echo "Starting IQ-TREE species tree inference"
echo "Alignment directory: $ALIGN_DIR"
echo "Output directory:    $OUTPUT_DIR"
echo "CPUs:                $NCPU"
echo "Start time:          $(date "+%Y-%m-%d %H:%M:%S")"
echo
echo "IQ-TREE version:"
iqtree3-mpi --version 2>&1
echo

############################
# Run IQ-TREE
############################

iqtree3-mpi \
    -p "${SCRATCHDIR}/iqtree_input" \
    --seqtype AA \
    -m MFP+MERGE \
    -rcluster 10 \
    -B 1000 \
    -alrt 1000 \
    -T "$NCPU" \
    --prefix "${SCRATCHDIR}/iqtree_output/${PREFIX}"

echo "Start copying output data." | ts '[%Y-%m-%d %H:%M:%S]'

# copy output data
mkdir -p "$OUTPUT_DIR"
cp -R ${SCRATCHDIR}/iqtree_output/* $OUTPUT_DIR

echo "Output data copying done." | ts '[%Y-%m-%d %H:%M:%S]'

############################
# Summary
############################

echo
echo "IQ-TREE analysis finished"
echo "End time: $(date "+%Y-%m-%d %H:%M:%S")"
echo
echo "Main output tree:"
echo "  ${OUTPUT_DIR}/${PREFIX}.treefile"

clean_scratch
```

```{sh}
cd /storage/brno12-cerit/home/duchmil/Brassicaceae_orthology/brassicaceae_3/metacentrum_scripts
qsub iqtree_species_tree.bash
```



